const body=document.body, modal=document.querySelector('#leadModal');document.querySelector('.menu')?.addEventListener('click',()=>body.classList.toggle('menu-open'));document.querySelectorAll('nav a').forEach(a=>a.addEventListener('click',()=>body.classList.remove('menu-open')));document.querySelectorAll('.leak-trigger').forEach(a=>a.addEventListener('click',e=>{if(location.pathname==='/'||location.pathname.endsWith('index.html')){e.preventDefault();modal?.classList.add('open');modal?.setAttribute('aria-hidden','false')}}));document.querySelector('.close')?.addEventListener('click',()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true')});modal?.addEventListener('click',e=>{if(e.target===modal){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}});document.querySelectorAll('.lead-form').forEach(form=>form.addEventListener('submit',async e=>{e.preventDefault();const btn=form.querySelector('.submit'),msg=form.querySelector('.form-msg'),data=Object.fromEntries(new FormData(form).entries());if(!data.Name||!data.Email||!data.Country||!data.Details){msg.textContent='Please add your name, email, country and enquiry numbers.';return}if(!/^\S+@\S+\.\S+$/.test(data.Email)){msg.textContent="That email address doesn't look right.";return}btn.disabled=true;btn.textContent='Sending…';msg.textContent='';try{const r=await fetch('/api/contact',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});if(!r.ok)throw Error();form.reset();msg.textContent="Got it. We'll reply within 24 hours."}catch(err){msg.textContent="That didn't go through. Try again, or email support@tuningcurvelabs.com."}finally{btn.disabled=false;btn.textContent='SEND ENQUIRY →'}}));
// V26 restrained reveal motion
const revealTargets=document.querySelectorAll('.section-head,.work-grid article,.framework article,.steps article,.why p,.three article,.team-card,.quotes blockquote,.start article,.faq details');
revealTargets.forEach(el=>el.classList.add('reveal'));
if('IntersectionObserver' in window){const io=new IntersectionObserver((entries)=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -40px'});revealTargets.forEach(el=>io.observe(el))}else{revealTargets.forEach(el=>el.classList.add('in'))}
// V27 adaptive header: hero/header share one canvas, then contrast follows the section below.
const siteHeader=document.querySelector('header');
function syncHeader(){if(!siteHeader)return;const y=siteHeader.offsetHeight/2+4;const probe=document.elementFromPoint(innerWidth/2,y);const section=probe?.closest('section,footer,main');const dark=section?.classList.contains('ink')||section?.classList.contains('blue')||section?.classList.contains('hero')||section?.tagName==='FOOTER';siteHeader.classList.toggle('scrolled',scrollY>18);siteHeader.classList.toggle('on-dark',!!dark);siteHeader.classList.toggle('on-light',!dark&&scrollY>18)}
addEventListener('scroll',syncHeader,{passive:true});addEventListener('resize',syncHeader);syncHeader();
const founderPhoto=document.querySelector('.founder-photo');founderPhoto?.addEventListener('click',()=>founderPhoto.classList.toggle('is-colour'));
